language: scala
scala:
  - "2.10.4"
# command to install dependencies
install:
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.4.0-bin-hadoop2.6.tgz"
  - "tar -xzf spark-1.4.0-bin-hadoop2.6.tgz"
  - "mkdir ~/bin"
  - "mv spark-1.4.0-bin-hadoop2.6 ~/bin/spark-1.4.0"
# command to run tests
script: ./run.sh